order-service:
  payment-request-topic-name: payment-request
  payment-response-topic-name: payment-response
  restaurant-approval-request-topic-name: restaurant-approval-request
  restaurant-approval-response-topic-name: restaurant-approval-response
  order-created-topic-name: order-created
  order-cancelled-topic-name: order-cancelled
  order-paid-topic-name: order-paid

spring:
  kafka:
    bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
