server:
  port: 8184

logging:
  level:
    com.food.ordering.system: DEBUG
    org.flywaydb: DEBUG

spring:
  jpa:
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=customer&binaryTransfer=true&reWriteBatchedInserts=true
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  ##Flyway
  flyway:
    enabled: true
    locations: classpath:db
    baseline-on-migrate: true
    schemas: customer
    default-schema: customer
    create-schemas: true